FROM registry.access.redhat.com/ubi9/openjdk-21:1.20-2.1721752936 as builder

# Jenkins plugins requires git to be present for the build.
USER root
RUN microdnf install -y git

USER 185

# The "package" goal creates the Jenkins .hpi that lets it be installed as a plugin.
ENV MAVEN_S2I_ARTIFACT_DIRS="target" \
    MAVEN_S2I_GOALS="clean package" \
    S2I_SOURCE_DEPLOYMENTS_FILTER="*.hpi"

# Copying in source code. Red Hat OpenJDK S2I buiders expect source content in /tmp/src by default
COPY --chown=185:0 pom.xml /tmp/src/pom.xml
COPY --chown=185:0 .mvn /tmp/src/.mvn
COPY --chown=185:0 src /tmp/src/src

RUN /usr/local/s2i/assemble

FROM registry.redhat.io/openshift4/ose-cli-rhel9:v4.17 as oc-4.17
FROM registry.redhat.io/openshift4/ose-cli-rhel9:v4.17 as oc-4.16
FROM registry.redhat.io/openshift4/ose-cli:v4.15 as oc-4.15
FROM registry.redhat.io/openshift4/ose-cli:v4.14 as oc-4.14
FROM registry.redhat.io/openshift4/ose-cli:v4.12 as oc-4.12

# Start from base "core controller" image on Konflux
FROM quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-jenkins-2-462/jenkins-core-controller-2-462@sha256:910cc4f57c8ba10472d08d7edf01f9d32ef5f04c3708b58b2bd49182da90d95e

USER root

# Copy our variants of the `oc` binary into the image, allowing them to be selected as a Jenkins tool.
# This can be set up using Jenkins Configuration as Code.
COPY --from=oc-4.17 --chown=root:root /usr/bin/oc /usr/share/openshift/bin/oc-4.17/
COPY --from=oc-4.16 --chown=root:root /usr/bin/oc /usr/share/openshift/bin/oc-4.16/
COPY --from=oc-4.15 --chown=root:root /usr/bin/oc /usr/share/openshift/bin/oc-4.15/
COPY --from=oc-4.14 --chown=root:root /usr/bin/oc /usr/share/openshift/bin/oc-4.14/
COPY --from=oc-4.12 --chown=root:root /usr/bin/oc /usr/share/openshift/bin/oc-4.12/

USER jenkins

COPY --chown=jenkins:jenkins .konflux/plugins.txt /usr/share/jenkins/ref/plugins.txt
COPY --from=builder --chown=jenkins:jenkins /deployments/openshift-aggregator.hpi /usr/share/jenkins/ref/openshift-aggregator.hpi

# For Jenkins, plugins should be installed using the `jenkins-plugin-cli` script. This installs the
# plugin and their dependencies.
RUN jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt
