# Helm values for enabling the OpenShift Login plugin
controller:
  JCasC:
    configScripts:
      openshift-login: |-
        jenkins:
          authorizationStrategy:
            globalMatrix:
              permissions:
                - "Overall/Administer:admin"
                - "Overall/Read:admin"
                - "Job/Build:admin"
                - "Job/Configure:admin"
                - "Job/Create:admin"
                - "Job/Delete:admin"
                - "Job/Read:admin"
                - "Job/Workspace:admin"
                - "Run/Delete:admin"
                - "Run/Update:admin"
                - "SCM/Tag:admin"
                - "View/Configure:admin"
                - "View/Create:admin"
                - "View/Delete:admin"
          securityRealm:
            openShiftOAuth2: {}
  route:
    enabled: true
# Name overrides needed for oauth-redirectreference
nameOverride: jenkins
fullNameOverride: jenkins
serviceAccount:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.jenkins: "{\"kind\":\"OAuthRedirectReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"Route\",\"name\":\"jenkins\"}}"
