# Minimum values for deploying Jenkins with the Helm chart
# Configuration for specific plugins is found in seprate `values_*.yaml` files
agent:
  enabled: true
  image:
    repository: quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-jenkins-2-462/jenkinsci-docker-agent-2-462
    tag: "latest@sha256:5c917185db5918391b7be0fadcd9314fa5df4856fc046fb0ceb98a1c0ce32eb5"
controller:
  image:
    registry: quay.io
    repository: redhat-user-workloads/rh-openshift-builds-tenant/openshift-jenkins-2-462/openshift-aggregator-plugin-2-462
    tag: a0511956962bfb07e8b37bea2437aefd4f0799fd
  installPlugins: false
  # Needed for OAuth2 plugin - TODO figure out how to get this from route status.
  jenkinsUrl: https://jenkins-jenkins.apps-crc.testing
  numExecutors: 5
  overrideArgs:
    - -pre
    - "echo 'Starting Jenkins'"
  prometheus:
    enabled: false
  sidecars:
    configAutoReload:
      enabled: false
rbac:
  create: true
  readSecrets: true
  useOpenShiftNonRootSCC: true
